DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE(
	id_image INT PRIMARY KEY NOT NULL,
	comment VARCHAR(255),
	creation_date TEXT,
	length int,
	width int,
	size int,
	path VARCHAR(255)
);

DROP TABLE IF EXISTS VECTOR;
CREATE TABLE VECTOR(
	id_vector INT PRIMARY KEY NOT NULL,
	value_vector VARCHAR NOT NULL,
	tag_name VARCHAR(255)
);

DROP TABLE IF EXISTS OBJECT_VECTOR;
CREATE TABLE OBJECT_VECTOR(
	id_vector INT NOT NULL,
	id_parent INT,
	FOREIGN KEY (id_vector) REFERENCES VECTOR(id_vector),
	FOREIGN KEY (id_parent) REFERENCES VECTOR(id_vector)
);

DROP TABLE IF EXISTS FACE_VECTOR;
CREATE TABLE FACE_VECTOR(
	id_vector INT NOT NULL,
	IsKnown int NOT NULL,
	FOREIGN KEY (id_vector) REFERENCES VECTOR(id_vector)
);

DROP TABLE IF EXISTS INCLUDE;
CREATE TABLE INCLUDE(
	id_vector INT NOT NULL,
	id_image INT NOT NULL,
	FOREIGN KEY (id_vector) REFERENCES VECTOR(id_vector),
	FOREIGN KEY (id_image) REFERENCES IMAGE(id_image)
);
