@startuml face_detection

title Reconnaissance faciale

actor User
boundary IHM
entity Tensorflow
database BackEnd

User->IHM: Clic sur une image de la gallerie
IHM->Tensorflow: Obtenir les rectangles des visages
IHM->BackEnd: Obtenir les descripteurs de l'image
IHM->BackEnd: Obtenir les descripteurs des personnes connues
IHM->User: Affichage de l'image et de ses tags

@enduml
